# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8aebfa59-88fc-4a64-a294-3781c9ba2790";
      fsType = "btrfs";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/8aebfa59-88fc-4a64-a294-3781c9ba2790";
      fsType = "btrfs";
      options = ["subvol=home"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/8aebfa59-88fc-4a64-a294-3781c9ba2790";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/1F86-EA33";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/17488396-de5c-4f3c-aaf1-e5256f148c0a";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
